services:
  image-generator:
    build: 
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "8080:8080"
    volumes:
      - ./output:/app/output
      - huggingface_cache:/root/.cache/huggingface
      - model_cache:/app/models  # Persistent storage for downloaded models

volumes:
  huggingface_cache:
  model_cache:  # Persistent volume for model storage
