x-common-config: &common-config
  build: 
    context: .
    dockerfile: Dockerfile
  env_file: .env
  ports:
    - "8080:8080"
  volumes:
    - ./output:/app/output

services:
  # CPU version (default)
  image-generator:
    <<: *common-config
    profiles: ["cpu"]

  # GPU version (use with --profile gpu)
  image-generator-gpu:
    <<: *common-config
    profiles: ["gpu"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [compute, utility]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True
