version: '3.8'

services:
  image-generator:
    build: 
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "8080:8080"
    volumes:
      - ./output:/app/output
    # GPU configuration will be applied only if USE_GPU=true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [compute, utility]
    environment:
      - NVIDIA_VISIBLE_DEVICES=${USE_GPU:+all}
      - NVIDIA_DRIVER_CAPABILITIES=${USE_GPU:+compute,utility}
      - PYTORCH_CUDA_ALLOC_CONF=${USE_GPU:+expandable_segments:True}
