services:
  image-generator:
    build: 
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "8080:8080"
    volumes:
      - ./output:/app/output
      - huggingface_cache:/root/.cache/huggingface
      - model_cache:/app/models

volumes:
  huggingface_cache:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '${PWD}/cache'
  model_cache:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '${PWD}/models'
