services:
  image-generator:
    build: 
      context: .
      dockerfile: Dockerfile
    env_file: .env
    environment:
      - PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True,max_split_size_mb:512
    ports:
      - "8080:8080"
    volumes:
      - ./output:/app/output
      - ./cache:/root/.cache/huggingface   # Bind mount for better control
      - ./models:/app/models               # Bind mount for better control
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
