version: '3.8'

# GPU configuration for services
x-gpu-config: &gpu-config
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            count: 1
            capabilities: [compute, utility]
  environment:
    - NVIDIA_VISIBLE_DEVICES=all
    - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    - PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True  # Help with memory fragmentation

services:
  image-generator:
    build: 
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "8080:8080"
    volumes:
      - ./output:/app/output
    <<: *gpu-config
